version: "2"

services:
  vermarine:
    build: .
    ports:
    - "8080:8080"
    - "8787:8787"
    image: vermarine/scheduler
    links:
    - mysql
    - test-server
    environment:
    - "VERAMINE_DATABASE_DRIVER=com.mysql.jdbc.Driver"
    - "VERAMINE_DATABASE_URL=jdbc:mysql://mysql/vermarine"
    - "VERAMINE_DATABASE_USERNAME=root"
    - "VERAMINE_DATABASE_PASSWORD=password"
    - "VERTX_OPTS='-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=8787'"

  mysql:
    build: src/main/mysql-example
    ports:
    - "3306:3306"
    image: vermarine/example-mysql

  test-server:
    image: nginx:latest
    ports:
    - "8081:80"
    volumes:
    - "./src/main/nginx-example:/usr/share/nginx/html"